// movie_rest.go — movie rest: starts a local HTTP server for the library API
package cmd

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/cobra"

	"github.com/alimtvnetwork/movie-cli-v8/db"
	"github.com/alimtvnetwork/movie-cli-v8/errlog"
)

var restPort int
var restOpen bool

var movieRestCmd = &cobra.Command{
	Use:   "rest",
	Short: "Start a local REST API server for the library",
	Long: `Starts a lightweight HTTP server that exposes your movie library
via REST endpoints. The HTML report generated by 'movie scan' can
communicate with this server for interactive features.

Default port: 8086. Override with --port.

Endpoints:
  GET    /api/media              List all media
  GET    /api/media/{id}         Get a single media item
  DELETE /api/media/{id}         Remove a media item
  PATCH  /api/media/{id}         Update media fields (JSON body)
  GET    /api/media/{id}/details Full modal payload (media + tags + similar)
  GET    /api/media/{id}/similar TMDb recommendations
  PATCH  /api/media/{id}/watched Mark as watched
  GET    /api/tags               All tags with counts
  GET    /api/tags?media_id=N    Tags for a specific item
  POST   /api/tags               Add a tag (JSON: media_id, tag)
  DELETE /api/tags               Remove a tag (JSON: media_id, tag)
  GET    /api/stats              Library statistics
  GET    /api/dashboard/filters  Distinct genres, tag counts, year range, type counts
  GET    /api/dashboard/list     Filterable + sortable + paginated card list

Examples:
  movie rest              Start on port 8086
  movie rest --port 9000  Start on port 9000
  movie rest --open       Start and open report in browser`,
	Run: runMovieRest,
}

func init() {
	movieRestCmd.Flags().IntVarP(&restPort, "port", "p", 8086,
		"port to listen on")
	movieRestCmd.Flags().BoolVar(&restOpen, "open", false,
		"open the HTML report in the default browser")
}

func runMovieRest(cmd *cobra.Command, args []string) {
	database, err := db.Open()
	if err != nil {
		errlog.Error(msgDatabaseError, err)
		return
	}
	defer database.Close()

	initRestLogger(database)
	mux := buildRESTMux(database)

	printRESTBanner()

	if restOpen || scanRest {
		go openBrowser(fmt.Sprintf("http://localhost:%d", restPort))
	}

	handler := logMiddleware(mux)
	addr := fmt.Sprintf(":%d", restPort)
	if srvErr := http.ListenAndServe(addr, handler); srvErr != nil {
		errlog.Error("Server error: %v", srvErr)
	}
}

func initRestLogger(database *db.DB) {
	if initErr := errlog.Init(database.BasePath, "rest"); initErr != nil {
		errlog.Warn("Could not init error logger: %v", initErr)
		return
	}
	errlog.SetDBWriter(func(e errlog.Entry) {
		if dbErr := database.InsertErrorLog(db.ErrorLogEntry{
			Timestamp: e.Timestamp, Level: string(e.Level), Source: e.Source,
			Function: e.Function, Command: e.Command, WorkDir: e.WorkDir,
			Message: e.Message, StackTrace: e.StackTrace,
		}); dbErr != nil {
			errlog.Warn("Could not write error to DB: %v", dbErr)
		}
	})
}

func buildRESTMux(database *db.DB) *http.ServeMux {
	mux := http.NewServeMux()

	thumbDir := filepath.Join(database.BasePath, "thumbnails")
	mux.Handle("/thumbnails/", http.StripPrefix("/thumbnails/", http.FileServer(http.Dir(thumbDir))))

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" && !strings.HasPrefix(r.URL.Path, "/thumbnails/") {
			http.NotFound(w, r)
			return
		}
		if r.URL.Path == "/" {
			serveHTMLReport(w, database, restPort)
		}
	})

	mux.HandleFunc("/api/tags", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleTags(w, r, database)
	}))
	mux.HandleFunc("/api/media", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleListMedia(w, r, database)
	}))
	mux.HandleFunc("/api/media/", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/api/media/")
		parts := strings.SplitN(path, "/", 2)
		if len(parts) == 2 {
			switch parts[1] {
			case "similar":
				handleSimilar(w, r, database)
				return
			case "watched":
				handleWatched(w, r, database)
				return
			case "details":
				handleMediaDetails(w, r, database)
				return
			}
		}
		handleMediaByID(w, r, database)
	}))
	mux.HandleFunc("/api/stats", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleStats(w, r, database)
	}))
	mux.HandleFunc("/api/logs", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleLogs(w, r, database)
	}))
	mux.HandleFunc("/api/dashboard/filters", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleDashboardFilters(w, r, database)
	}))
	mux.HandleFunc("/api/dashboard/list", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleDashboardList(w, r, database)
	}))
	mux.HandleFunc("/api/dashboard/export", corsWrap(func(w http.ResponseWriter, r *http.Request) {
		handleDashboardExport(w, r, database)
	}))

	return mux
}

func printRESTBanner() {
	url := fmt.Sprintf("http://localhost:%d", restPort)
	fmt.Printf("\n🚀 Movie CLI REST server running on %s\n", url)
	fmt.Println("   Press Ctrl+C to stop")
	fmt.Printf("   Endpoints:\n")
	fmt.Printf("     GET    /                       HTML library report\n")
	fmt.Printf("     GET    /api/media\n")
	fmt.Printf("     GET    /api/media/{id}\n")
	fmt.Printf("     DELETE /api/media/{id}\n")
	fmt.Printf("     PATCH  /api/media/{id}\n")
	fmt.Printf("     GET    /api/media/{id}/details\n")
	fmt.Printf("     GET    /api/media/{id}/similar\n")
	fmt.Printf("     PATCH  /api/media/{id}/watched\n")
	fmt.Printf("     GET    /api/tags\n")
	fmt.Printf("     GET    /api/tags?media_id={id}\n")
	fmt.Printf("     POST   /api/tags\n")
	fmt.Printf("     DELETE /api/tags\n")
	fmt.Printf("     GET    /api/stats\n")
	fmt.Printf("     GET    /api/dashboard/filters\n")
	fmt.Printf("     GET    /api/dashboard/list?type=&genre=&tag=&q=&min_rating=&year_from=&year_to=&sort=&limit=&offset=\n")
	fmt.Printf("     GET    /api/logs?level=ERROR&limit=50\n\n")
}

// openBrowser opens the given URL in the default browser.
func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		cmd = exec.Command("xdg-open", url)
	}
	if err := cmd.Start(); err != nil {
		errlog.Warn("Could not open browser: %v", err)
	}
}

// corsWrap adds CORS headers so the HTML report can call the API.
func corsWrap(handler http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PATCH, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		handler(w, r)
	}
}

func handleListMedia(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	items, err := database.ListMedia(0, 10000)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, items)
}

func handleStats(w http.ResponseWriter, r *http.Request, database *db.DB) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	total, _ := database.CountMedia("")
	movies, _ := database.CountMedia(string(db.MediaTypeMovie))
	tv, _ := database.CountMedia(string(db.MediaTypeTV))
	writeJSON(w, map[string]int{"total": total, "movies": movies, "tv_shows": tv})
}

func writeJSON(w http.ResponseWriter, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(data); err != nil {
		errlog.Error("JSON encode error: %v", err)
	}
}
